server:
  port: 8010

spring:
  application:
    name: test-10-fastdfs
  datasource:
    dynamic:
      primary: test
      datasource:
        test:
          url: jdbc:mysql://localhost:3306/test?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
          username: root
          password: root
          driverClassName: com.mysql.cj.jdbc.Driver
        springcloud_db01:
          url: jdbc:mysql://localhost:3306/springcloud_db01?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true
          username: root
          password: root
          driverClassName: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /static/**

# fastdfs 配置，连接超时时间、读取超时时间、生成缩略图参数、tracker地址
fdfs:
  connect-timeout: 120
  so-timeout: 2000
  thumb-image:
    height: 150
    width: 150
  tracker-list: 192.168.3.22:22122,192.168.3.23:22122

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.test.fastdfs.mapper
#  configuration: #配置此种打印方式会在控制台打印出sql和参数，及sql执行的所有结果集
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#配置此种打印方式只会在控制台打印出sql及参数，不会打印出sql执行的所有结果集
logging:
  level:
    com.test.fastdfs: debug